import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const notoSerifBangali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBangali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>
          <Header></Header>
        </div>
        {children}
        <div className="bg-base-300 w-full">
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
